## Up, Down, and Through

Those that travel extensively will eventually encounter some person that seems very familiar yet wildly bizarre. The feeling generated by these encounters is described as being *up, down, and through*. It has become a common enough expression that some people are described as being from The Up Down and Through.

Travellers from the Up Down and Through come in various shapes and sizes. The simultaneous sensations of predictability and vast possibility can create the most memorable encounters, even if they can be a bit unnerving.